import React, { useEffect, useRef, useState } from "react";
import { Helmet } from "react-helmet";
import {
  getNewQuestion,
  randomHexColorArr,
  randomNumThree,
} from "./utils/utils";

export interface Guess {
  correctAnswer: string;
  choices: string[];
}
export type NotifMsg = {
  status: "correct" | "incorrect";
  msg: string;
};
const App: React.FC = () => {
  const ref = useRef<HTMLDivElement>(
    null
  ) as React.MutableRefObject<HTMLInputElement>;
  const [notifMsg, setNotifMsg] = useState<NotifMsg | null>();

  const initialChoices = randomHexColorArr();
  const [currQuestion, setCurrQuestion] = useState<Guess>({
    correctAnswer: initialChoices[randomNumThree()],
    choices: initialChoices,
  });

  const handleChoiceClick = (choiceMade: string) => {
    if (!currQuestion.correctAnswer) return;
    if (choiceMade === currQuestion.correctAnswer) {
      setNotifMsg({
        status: "correct",
        msg: `Congrats, you got it Right!`,
      });
    } else {
      setNotifMsg({
        status: "incorrect",
        msg: `${choiceMade} is incorrect! The correct answer was ${currQuestion.correctAnswer}`,
      });
    }
  };
  useEffect(() => {
    const callFirstChoices = async () => {
      await handleNext();
    };
    callFirstChoices();
  }, []);

  const handleNext = async () => {
    setNotifMsg(null);

    const newQuestion = getNewQuestion();

    if (ref.current) {
      const randomColor: string =
        newQuestion.choices[Math.floor(Math.random() * 3) + 1];
      ref.current.style.backgroundColor = randomColor;
    }
    await setCurrQuestion(newQuestion);
  };

  const notifStatusStyle = (status: "correct" | "incorrect") => {
    if (status === "correct") {
      return "bg-teal-500 text-white";
    } else {
      return "bg-red-200 text-red-900";
    }
  };

  return (
    <>
      <Helmet>
        <title>LetsHex Color Guessing Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>

      <div className="relative h-screen w-full flex items-center justify-center bg-slate-200">
        <div className="absolute left-10 top-10 w-full mb-5 flex items-center justify-between">
          <div className="flex items-center">
            <div className="text-4xl font-extrabold mb-1 mr-1 tracking-tighter">
              LetsHex
            </div>
            <div className="font-light text-2xl">| Hex Color Guessing game</div>
          </div>
          <div className="font-light text-2xl">By Ahmad Sandid</div>
        </div>
        <div className="absolute top-5 left-0 w-full h-24 px-10  flex items-center justify-center">
          <div
            className={`w-auto h-full rounded-2xl flex items-center text-lg font-semibold px-10 duration-300 ${
              notifMsg ? "opacity-100" : "opacity-0"
            }
            ${notifMsg && notifStatusStyle(notifMsg.status)}`}
          >
            {notifMsg ? notifMsg.msg : ""}
          </div>
        </div>
        <div className="relative h-[60vh] w-[70vw] p-10 flex flex-col justify-center items-center rounded-[2rem] bg-white shadow-[2rem]">
          <div className="absolute left-10 top-10 text-4xl font-extrabold mb-1 mr-1 tracking-tighter">
            LetsHex
          </div>
          <div className="flex h-64 w-full mb-5">
            <div className="h-full w-1/2 flex items-center text-6xl font-extrabold tracking-tighter">
              Whats the Color? 😦
            </div>
            <div ref={ref} className={`w-1/2 h-full rounded-2xl`} />
          </div>
          <div className="w-full h-32 flex gap-3">
            {currQuestion.choices.map((choice) => (
              <div
                key={choice}
                onClick={() => handleChoiceClick(choice)}
                className="h-full w-1/3 rounded-2xl select-none hover:-translate-y-0.5 hover:shadow-xl border-2 border-neutral-200 cursor-pointer duration-300 flex items-center justify-center text-2xl font-semibold"
              >
                {choice}
              </div>
            ))}
          </div>
          <div
            onClick={handleNext}
            className="bg-slate-300 select-none text-slate-900 hover:bg-slate-500 hover:text-slate-50 duration-300 cursor-pointer py-2 px-5 mt-5 rounded-xl font-bold"
          >
            Next Question
          </div>
        </div>
      </div>
    </>
  );
};

export default App;
